apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |

    server {
      listen 80;
      root /var/www/html;

      # Add index.php to the list if you are using PHP
      index index.php index.html index.htm;

      location / {
          try_files $uri $uri/ /index.php?$query_string;
          gzip_static on;
      }

      location ~ \.php$ {
          try_files $uri =404;
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_index index.php;
          fastcgi_read_timeout 14400s;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $request_filename;
          fastcgi_param PATH_INFO $fastcgi_path_info;
      }

      location /doc/ {
          alias /var/www/html/apidoc/;
      }

      error_page  404               /404.html;
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/local/www/nginx-dist;
      }
      gzip On;
    }

  index.html: |

    <html><head><title>Code Education</title></head>
    <body>Code.education Rocks</body>
    </html>
